{% set name = "diffoscope" %}
{% set version = "88" %}
{% set sha256 = "e25664b5aea0d0610879bf82d219cc97743a0b67236abcc8eb5abf78c6b2e6fe" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win or py2k]

requirements:
  build:
    - python
    - python-magic
    - setuptools
  run:
    - python
    - python-libarchive-c
    - python-magic
    - setuptools

test:
  imports:
    - diffoscope
  commands:
    - diffoscope --help
    - diffoscope --list-tools
    - diffoscope --version

about:
  home: https://diffoscope.org
  license: GPL-3.0
  summary: in-depth comparison of files, archives, and directories
  license_family: GPL
  license_file: COPYING
  dev_url: https://anonscm.debian.org/cgit/reproducible/diffoscope.git
  description: >
    diffoscope will try to get to the bottom of what makes files or
    directories different. It will recursively unpack archives of many kinds
    and transform various binary formats into more human readable form to
    compare them. It can compare two tarballs, ISO images, or PDF just as
    easily.

extra:
  recipe-maintainers:
    - bollwyvl
