travis:
  secure:
    BINSTAR_TOKEN: dcREgngLq8EPiSovoVzwZKATcQ9uFtcv0UJiimXHQY1JvblSqZtYTk198rmAXfLYKNE+eC/oC2ihJtyneTZF6obJjl5863FqjenBxFUe5SmmgGDYKsMCYxbg3VEMhIoYQTHow7HTXktR4h6uh2M2w1jvedskhpfcJ+3tEgG7hAEyVm2kmlfhNlr3aAh08JDWvNffmz6OPM/4u8b6Uhi16dUkSfb/AYmdn2/ILkrl2p+HnqABoIfJxECqKp8Va0wuhbmqYmEFN8F6R/p/GhctM8bKe0nHDWCv9XY9IzSUoWs7yaRlvnT8dOpyDfypRvcKU1JncByurAH7CLrgpnIeprr4der/7kTiEIE5r8HvWF3xjRSYkF9jMl6psv5oIpVy9SyC7tmOOJDgnshjkR95pbkvlXmRhSQrRjmuchzwrVIWK3V9xvcwq0ckB+2y8DDe+SD1bcMNm7eAAqeXq1DiI5+ESUMrevvzbDb7udNkA8scTXssFYUY/KD4zxvNVhatZT6GazEiwFNhdiI5olPzqRd1oJ4WCRRs9fxOIO4m4enykE2JDuEMkGKd66UcGN8PBRRs+SgiulpHriP8Lb1MGS3fWXm3tF5zUFA+Ik6dVCdc/DnqeMxlbM1CteHdVNjQVQIwzGm80lDaL1y3Hd/M79in41Kl9ISdeiehyTaZbWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
