travis:
  secure:
    BINSTAR_TOKEN: TWC7At4Dtkd+a3Nxu0wZvCIq4OkLzSQZVwJoqjUdI5bmNryo/bBVC1MQXyRK+fW5P5pZyfGdFcSD7ihMfQOqjpcZ8zzFhbOT1Uw93wFqu8pqXZuBugU2u6JvsJOXeKmlJmjwv2Aq9Ig/b4wnE55PY1TeKZPJ7jmqHzhI+iX5Pq8tE15mk9wComuuRR4byAQg8Cy0JdVblBSKQWI3w1scvqhculZP7dkzfpgnuhZl0QF7hih2YFyar3cybGB+OhmVy0X9y+KlucMyyt+uFNrw/VfBiWQX2IY9IeCgnumzLj755kd5d1q/gVg7LYnlkFuBQit5iv3iKZxgKlJokD9SJl2VJkkm2YXEQJaDEtN6sr9mzH0jNKlPNfraf4NeyfzGqAVVaT617VXkb2iiLZ3IWSkZasYtvwoLC/tQFpJFOfgy3yw62XB4QTvJCxnyvIiODMY+5wvdVFpewQr8ZHoNR8ZbGeL0i2r4xXxT2/z6l29Gik/vHVbhmVv3vBfvuM8bl9X9KFyJyrW3L0IE6uMm+k6FKMUXQVpX+eC1bgyXDVr9KiiZobldM4LZgMmxb3t5wL6ZMyF2L8ttA45eVMHn3v8ucbcflVwqeQlO8zLLZM1/VN+tWa+LJRePxGALdulimfttnqhKFH2GD0jSL/wgrj7A3wYiEISoeqKTYKe+/4I=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
